# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1COtS7WKLAu1BNmHv-LyhpC6MCICwb-C8
"""

#1
length = int(input("enter the length of rectangle in m. : "))
width = int(input("enter the width of rectangle in m.: "))
area = length * width
print(f"area of rectangle is :{area} m^2")

#2
w = float(input("enter the weight : "))
h = float(input("enter the height : "))
r = h*h
bmi = w/r
print(f"the bmi is = {bmi} ")

#3
n = int(input("how many students data you have :"))
student_data = {}
for i in range(n):
  name = input("enter the name of student : ")
  score = int(input("enter the score of student"))
  student_data[name]=score
print(student_data)

#4
age = int(input("enter the age of user : "))
if(age>=60):
  print("senior")
elif(age>=18 and age<60):
  print("adult")
else:
  print("minor")

#5
for i in range(50):
  print(i+1)

#6
p = "panindia"
r = input("enter the password : ")
while True:
  if(p == r):
    print("password is correct")
    break
  else:
    print("password is incorrect")
    break

#7
def avg(l1,l2):
  av = l1+l2/2
  return av
a = int(input("enter the first number: "))
b = int(input("enter the second number: "))
r = avg(a,b)
print(r)

#8
def count_vowels(s):
    vowels = 'aeiouAEIOU'
    vowel_count = 0
    for char in s:
        if char in vowels:
            vowel_count += 1
    return vowel_count

string = "Hello, World!"
print("Number of vowels:", count_vowels(string))

#9
import datetime

current_datetime = datetime.datetime.now()
print("Current date and time:", current_datetime)

#10
try :
  av = int(input("enter any number :"))
  print("given number is numeric :")
except:
  print("invalid operation")

#11
try :
  num = int(input("enter any integer : "))
  print(num)
except:
  print("invalid operations")

#12
a = int(input("enter a number :"))
b = int(input("enter second number :"))
try:
  def divide(c,d):
    r = c/d
    print(r)
except:
  print("invalid operations")
a = divide(a,b)

#13
with open("hello.txt", "w") as file:
    file.write("Hello Python\n")

print("Successfully wrote 'Hello Python' to hello.txt")

#14
with open("hello.txt", "r") as file:
    contents = file.read()

print("Contents of hello.txt:")
print(contents)

#15
with open("hello.txt", "a+") as file:
    file.write("\nThis is a new line of text.")


with open("hello.txt", "r") as file:
    contents = file.read()

print("Updated contents of hello.txt:")
print(contents)